### ISSUE TITLE
install.bat doesnt create run.bat

### ISSUE THREAD

**Issue by aerthel** [Newms34/arc-check#1]
I ran install.bat (from windows explorer) and it didnt create any run.bat file to drag around.
I ran it for a second time from the CMD and i got
```
C:\Juegos\Guild Wars 2>install.bat

C:\Juegos\Guild Wars 2>echo off
Python 3.9.6
Requirement already satisfied: wget in c:\users\felipe\appdata\local\programs\python\python39\lib\site-packages (from -r ac-data/requirements.txt (line 1)) (3.2)
Requirement already satisfied: colorama in c:\users\felipe\appdata\local\programs\python\python39\lib\site-packages (from -r ac-data/requirements.txt (line 2)) (0.4.4)
Traceback (most recent call last):
  File "C:\Juegos\Guild Wars 2\ac-data\setup.py", line 12, in <module>
    for line in file:
  File "C:\Software\Python\lib\fileinput.py", line 249, in __next__
    line = self._readline()
  File "C:\Software\Python\lib\fileinput.py", line 343, in _readline
    os.rename(self._filename, self._backupfilename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'ac-data/run.bat' -> 'ac-data/run.bat.bak'
Please drag "run.bat" to a convenient location!
```

**Comment by Newms34** [comment]
Thanks! Lookin now!

**Comment by Newms34** [comment]
Should be fixed now! Stoopid permissions. Stoopid filewriting API.
